Added missing docs as per style guide #69
Still getting there errs, don't know why:

ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project robot-core: Error during page generation: Error rendering Maven report:
[ERROR] Exit code: 1 - /Users/cjm/repos/robot/robot-core/src/test/java/org/obolibrary/robot/MaterializeOperationTest.java:9: error: package org.obolibrary.robot.exceptions does not exist
[ERROR] import org.obolibrary.robot.exceptions.OntologyLogicException;
[ERROR] ^
[ERROR] /Users/cjm/repos/robot/robot-core/src/test/java/org/obolibrary/robot/MaterializeOperationTest.java:31: error: cannot find symbol
[ERROR] throws IOException, OWLOntologyCreationException, OntologyLogicException {
[ERROR] ^
[ERROR] symbol:   class OntologyLogicException